### ISSUE TITLE
Build instructions don't apply to current project in master

### ISSUE THREAD

**Issue by nicarq** [Fonta1n3/FullyNoded#109]
If you try to follow the building instructions from:  https://github.com/Fonta1n3/FullyNoded/blob/master/Docs/Build-from-source.md

it won't work because there is no carthague file so you get something like:

``` 
carthage build --platform iOS
*** xcodebuild output can be found in /var/folders/ky/f6zswf6s13qg70cnl9rjs6tr0000gn/T/carthage-xcodebuild.PYnYZr.log
Failed to read file or folder at /Users/X/FullyNoded/FullyNoded/Cartfile.resolved: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile.resolved” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/X/FullyNoded/FullyNoded/Cartfile.resolved, NSUnderlyingError=0x7f8ca1674a50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
``` 

The dependencies are already compiled in the project, so you still can compile it, if you go to Build Phases and comment this line in `Run Script`

`#/usr/local/bin/carthage copy-frameworks` 

<img width="1251" alt="Screen Shot 2020-09-29 at 11 39 47 PM" src="https://user-images.githubusercontent.com/1622112/94640699-601c5780-02ad-11eb-9dcd-75d80c88914b.png">

**Comment by Fonta1n3** [comment]
Correct! Just git clone and run the project now.

**Comment by Fonta1n3** [comment]
https://github.com/Fonta1n3/FullyNoded/commit/e8fb01f660427b1ab18a48c7ec6f6108193f5e9d
