### ISSUE TITLE
"Keys can only be added when private keys are disabled"

### ISSUE THREAD

**Issue by mcsnubbs** [Fonta1n3/FullyNoded#11]
I get this error when attempting to load my Coldcard xpub into a new wallet using the app and following your tutorial on youtube. Any way around this?

Thanks!

**Comment by Fonta1n3** [comment]
you should only get that when importing an xprv. you were definitely importing an xpub?

Please try the next testflight update (v0.1.21) and let me know if it happens again as it has some code changes around this.

**Comment by Fonta1n3** [comment]
@mcsnubbs this is fixed in latest push. should be live in testflight in the next day or so. full xprv import support enabled.
