### ISSUE TITLE
Adjust lightning port recommendation

### ISSUE THREAD

**Issue by elvece** [Fonta1n3/FullyNoded#116]
The recommended port to use for the c-lightning-http-plugin is `8080`. Suggested to change the default ports in this view to avoid confusion. 

![IMG_F536860F551B-1](https://user-images.githubusercontent.com/12953208/97634664-b0e1b600-19fb-11eb-89d2-9acad986828a.jpeg)

**Comment by Fonta1n3** [comment]
Good point, will make that change.
