### ISSUE TITLE
Failing bitcoin node connection with Tor v3 address

### ISSUE THREAD

**Issue by elvece** [Fonta1n3/FullyNoded#119]
**Bug**
Trying to connect a Tor v3 bitcoin node address and RPC credentials to FullyNoded on iOS. Scanning a QR code generated with the format: `btcstandup://<username>:<password>@xxx.onion:8332/`, I get the error denoted in the screenshot below. Suggested steps followed, but error is consistently reproducible. 

Debugging revealed a status code response of `401`, a `Content-Length: 0` header, and `Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}`. The receiving node does not seem to get the Authorization header (possibly why the 401).

Can verify the node is accessible by 
```curl --socks5-hostname localhost:9050 -XPOST -d'{"jsonrpc":"1.0","id":"curltest","method":"getblockchaininfo","params":[]}' http://<username>:<password>@xxx.onion:8332/```, which returns the expected response.

**To Reproduce**
1. Go to setttings to add a new bitcoin node
2. Click (+)
3. Click the QR code scanner button
4. Scan quick connect url (or enter credentials manually, the same result happens)
5. Save node
6. See error thrown

**Expected behavior**
A user should be able to add a bitcoin node with a Tor v3 address.

**Screenshots**
<img width="413" alt="Screen Shot 2020-11-04 at 1 37 15 PM" src="https://user-images.githubusercontent.com/12953208/98165311-e591b980-1ea2-11eb-84ff-a2fbefd73d20.png">

**Device**
 - Model: iPad Pro
 - OS: iOS 13.6
 - Version: v0.1.99

**Comment by Fonta1n3** [comment]
Hmmm V3 works.

Have you tried rebooting Tor on your node?

Are you using V3 authentication?

Are you absolutely sure the credentials are being added correctly?

**Comment by elvece** [comment]
Yes - have rebooted Tor, not using V3 auth. The creds are in the quick connect url string in the format `btcstandup://<username>:<password>@xxx.onion:8332/` - this is what is encoded in the QR code being scanned. Verified the node URL and credentials are correct - can curl the node with those RPC creds and obtain the expected response.

**Comment by Fonta1n3** [comment]
The auth is basic http auth. With the added ability to utilize tor v3 authentication: https://matt.traudt.xyz/p/FgbdRTFr.html

**Comment by Fonta1n3** [comment]
https://github.com/Fonta1n3/FullyNoded/commit/accbfe4e8e6eb9917c37fca37f751f3d948d991d fixes this, which was caused by the btcrpc 3rd party wrapper around bitcoin core refusing to respond to `www-authenticate` http header. Next update will switch to `Authenticate` http header to ensure compatibility.
