### ISSUE TITLE
Importing Cobo Vault Wallet via QR hangs on "Importing" 

### ISSUE THREAD

**Issue by flyingfaders** [Fonta1n3/FullyNoded#120]
I'm running the latest version of the BTC only firmware on my Cobo Vault and the latest version of FullyNoded. When trying to add a watch only wallet on Testnet, FullyNoded hangs at the importing screen. On my Bitcoin Core node I don't see any communication happening in the logs from FullyNoded. Can create hot wallets from FullyNoded no problems. 

1. "+" New Wallet in FullyNoded
2. Import via QR
3. Scan Cobo Vault's "Export Wallet" QR Code
4. Hangs on "importing"

**Comment by Fonta1n3** [comment]
Thanks for the bug.

Not sure what QR format Cobo is using.

Do you know of any docs where I can get an example QR to test against or would you mind sharing yours if it is testnet?

**Comment by flyingfaders** [comment]
Yep, I think their integration guide would cover it [Integration_guide.md](https://github.com/CoboVault/cobo-vault-docs/blob/master/Integration_guide.md) :)

**Comment by Fonta1n3** [comment]
Next update will support cobo wallet exports.

Only exception being multisig wallet QR, you must do that via file.

You can however scan the multisig keystore QR when creating an msig.
