### ISSUE TITLE
Address Explorer 

### ISSUE THREAD

**Issue by flyingfaders** [Fonta1n3/FullyNoded#122]
Would be great to have a nice Table View layout with all of the invoices / address you've created and if they have associated  txs on them.

Rough idea would be something like:

- A table view for receiving addresses and the ability to tap on an address have have the invoice QR code window open 

- A table view for change addresses. I feel that having them on a separate view would help when verifying transaction on a hardware device 

I haven't been able to find an obvious way to find the address explorer other than through the Wallet Details page. Would make it really great to have FullyNoded as an additional device to quickly verify addresses are correct when working with hardware wallets.

**Comment by Fonta1n3** [comment]
You can go to wallet details > copy the `receive descriptor keypool` and `change descriptor keypool` then with either of those values go to `tools` from the home screen `wallet` > `derive addresses` and paste in that descriptor. The receive descriptor will derive 0-2500 invoice addresses and the change descriptor will derive 0-2500 change addresses.

FN does not keep track of each invoice you produce, but your node does keep track of any used address. You can go via `tools` > `wallet` > `list address groups` which:

"The listaddressgroupings RPC lists groups of addresses that may have had their common ownership made public by common use as inputs in the same transaction or from being used as change from a previous transaction."

In English it lets you know which addresses in your wallet have been used, their label and if they have a current balance.

**Comment by Fonta1n3** [comment]
If you are unsure what each `tool` does, just use it and there will be a `help` button in the top right which fetches the help description for that rpc command direct from Bitcoin Core.

**Comment by Fonta1n3** [comment]
Fyi 0.2.2 has ability to toggle between change/receive addresses in the address explorer. Tappable table view will come later 👍

**Comment by flyingfaders** [comment]
Awesome! Just tested out the update. Works great 👍
