### ISSUE TITLE
Verify & Send Screen Text Overflow

### ISSUE THREAD

**Issue by flyingfaders** [Fonta1n3/FullyNoded#123]
At the Verify & Send screen long text fields overflow off the screen and make it difficult to 100% verify the addresses and the total fee.
 - Model: iPhone SE 2020

![Verify_Send_1](https://user-images.githubusercontent.com/67905545/99194616-9d449680-27d4-11eb-8207-b398337e6780.jpeg)
![Verify_Send_2](https://user-images.githubusercontent.com/67905545/99194618-a03f8700-27d4-11eb-8c85-d182e6877923.jpeg)

**Comment by Fonta1n3** [comment]
yea its on the to do list 👍
