### ISSUE TITLE
sats the standard

### ISSUE THREAD

**Issue by nolim1t** [Fonta1n3/FullyNoded#124]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Would like an option to display everything in sats (Lightning already does in transaction history), but onchain and total balance would be good too.

**Describe alternatives you've considered**
Haven't found an alternative yet (but using lightning through this tool seems to somehow "fix" the issue of using sats.

**Additional context**
I think its better UX if theres less decimal places. Eventually as bitcoin prices rise a smaller unit should be eventually used.

**Comment by Fonta1n3** [comment]
sounds good to me, will add it to the list 👍

**Comment by Fonta1n3** [comment]
Done for next release
