### ISSUE TITLE
About Tor V3 Auth Keypair

### ISSUE THREAD

**Issue by RachChou** [Fonta1n3/FullyNoded#13]
I'm confused that you only use one keypair and use QRCODE to pass the private key. Because in my mind, multiple key-pairs should be generated by the clients and provided to the server public key. Does using just one keypair cause no security issues?

**Comment by Fonta1n3** [comment]
The private key is not exported by QR code, only the public key. The private key is created by the device and is not accessible to the user. But I do allow users to do this manually so you can import your own private key if you want to create your own. I do not think only having one keypair is a security risk, but I am not an expert and am open to suggestions/explanations. What is the benefit of one client holding more then one keypair?

**Comment by RachChou** [comment]
Sorry, I may have misinterpreted the phrase "The private key is for Fully Noded (paste it or scan it as a QR code when you add your node)". I mistakenly think that the QR code here is the private key provided by the server to all clients. Thank you for your response
