### ISSUE TITLE
‘go’ keyboard button should activate ‘next’ on password screen

### ISSUE THREAD

**Issue by shawnyeager** [Fonta1n3/FullyNoded#131]
**Is your feature request related to a problem? Please describe.**
When entering the password at the login screen, the 'go' button on the iOS keyboard does not trigger 'next' beneath the password field. 

**Describe the solution you'd like**
It should do so. 

**Additional context**
![image](https://user-images.githubusercontent.com/980297/101696703-cb856100-3a76-11eb-8435-e10c28b00a89.png)

**Comment by Fonta1n3** [comment]
i agree! I had a really odd bug happening though so removed that functionality, will get back to this at some point though. Thanks
