### ISSUE TITLE
make compatible with LND for lightning wallet

### ISSUE THREAD

**Issue by josibake** [Fonta1n3/FullyNoded#136]
**Is your feature request related to a problem? Please describe.**
Most full node options today use LND (raspiblitz, umbrel) and currently there is no way to use fully noded as a bitcoin and LN wallet if you are using one of those options for your full node.

**Describe the solution you'd like**
Support for LND.

**Describe alternatives you've considered**
An alternative would be to run a separate c-lightning instance on my full node, but I haven't fully explored this.

**Comment by Fonta1n3** [comment]
Indeed, it is on the to do list.

**Comment by Fonta1n3** [comment]
this has been committed, closing for now. When its released (next update) please to try it out.
