### ISSUE TITLE
Node manager layout is not ok on iPhone SE

### ISSUE THREAD

**Issue by dimaatmelodromru** [Fonta1n3/FullyNoded#14]
Keyboard covers 1/2 (height) of RPC password input field.
Keyboard doesn't appear on screenshot hence no screenshot.

**Comment by Fonta1n3** [comment]
Hey thanks, will fix SE UI issues

**Comment by Fonta1n3** [comment]
Thanks again! Please report any other issues you find.

fixed as per https://github.com/Fonta1n3/FullyNoded/commit/efec247856e16227eee0d4e1d25f3442c318b8c8

Will be on the next testflight update and eventually to app store.
