### ISSUE TITLE
Changing RPC Password not picked up

### ISSUE THREAD

**Issue by MattDHill** [Fonta1n3/FullyNoded#143]
**Describe the bug**
It appears that changing a node's RPC Password is getting picked up.

**To Reproduce**
1. Change RPC Password in Core node
2. In Fully Noded, go to 'Node Manager --> Bitcoin Core Node'
3. Update RPC Password to match new password and hit "Save"
4. Fully Noded fails to connect
5. Observe logs in Bitcoin Core showing `ThreadRPCServer incorrect password attempt from <host>`

The problem can be resolved by deleting the node from Fully Noded, then adding it again with the new credentials.

**Device (please complete the following information):**
 - Model: iPhone 6s
 - OS: iOS
 - Version 13.5.1

**Comment by Fonta1n3** [comment]
Hey @MattDHill 

Did you reboot bitcoind after changing the rpcpassword?

**Comment by MattDHill** [comment]
If you cannot reproduce by just changing your RPC pass, restarting Bitcoind, then editing the pass field in FN, let me know, and I will dig deeper.

**Comment by Fonta1n3** [comment]
@MattDHill I was not able to reproduce this. Only difference is I am working with a local node, I can not test against my onion node as Tor V3 seems to be down again :(

Any chance you can see if this is reproducible on your end with a local node where the address in the FN Node Manger is set to `127.0.0.1:8332`?

**Comment by Fonta1n3** [comment]
Unable to replicate and no further info provided... please reopen if you can replicate.
