### ISSUE TITLE
In recovery, add ability to try multiple passphrases.

### ISSUE THREAD

**Issue by bitcoincoredotbin** [Fonta1n3/FullyNoded#144]
I'm helping a friend recover a wallet and the recovery tool is a great and easy way to do it.

He knows his seed but forgot his passphrase. "It's can only be one of 5 different passwords" "I use the same password i wouldnt forget" "the wallet forgot my password" kind of situation.

I have a list of his possible passphrases with a vaild BIP39 seed. It would be cool to have an advanced option to put in alternate passphrases so a user doesn't have to input the seed and re-scan multiple times. I know this would take much longer than a normal import since every phrase is a (new wallet)*(derivation paths), but it could save time in this specific situation.

**Comment by Fonta1n3** [comment]
To be honest you can only add one at a time... This won't change, you will just have to add each one individually.
