### ISSUE TITLE
"Looks like node is not on" -- Evidently having a connection issue?

### ISSUE THREAD

**Issue by hayduke-lives** [Fonta1n3/FullyNoded#146]
Running Bitcoin Core on OSX (Big Sur) and installed Fully Noded. I'm in the node manager and entered the RPC username/pw that's in the bitcoin.conf file (those are the only two lines in that file) and, because both Core and Fully Noded are on the same machine, I'm using the 127.0.0.1:8332 address.

When I hit save I get a success message but then Fully Noded gives me this:
Looks like your node is not on, make sure it is running and try again.

Core is most definitely running. The block chain has fully downloaded, it's connected to 10 peers so everything on that side of the equation looks to be working fine.

I'm at a loss. And I apologize if I'm missing something basic, this is my first time setting up a node & running FN. Any guidance is appreciated!

**Comment by Fonta1n3** [comment]
Are you running on Mainnet or testnet?

**Comment by hayduke-lives** [comment]
I don't believe I'm running either, had to look those up to see what they are. This computer is a fresh install so essentially the only apps I'm running are Bitcoin Core, Fully Noded, Mozilla, and Jump Desktop (a remote desktop app).

I've opened port 8333 through my router and allowed all incoming connections to Bitcoin Core through the OSX firewall, things connect fine via https://bitnodes.io/#join-the-network though that's all external so I'm not sure if any of it actually pertains to this issue.

**Comment by Fonta1n3** [comment]
You can try adding `server=1` to your bitcoin.conf file then reboot bitcoind and see if it helps.

**Comment by hayduke-lives** [comment]
Thanks, I think that might've done it!
