### ISSUE TITLE
Sign tx layout problem on iPhone SE

### ISSUE THREAD

**Issue by dimaatmelodromru** [Fonta1n3/FullyNoded#15]
![9FDD0306-0810-4B18-A9E9-9E23A6FF8560](https://user-images.githubusercontent.com/4951450/79082892-1a85c580-7d33-11ea-98ad-5fac70545d61.jpeg)

**Comment by Fonta1n3** [comment]
fixed as per https://github.com/Fonta1n3/FullyNoded/commit/efec247856e16227eee0d4e1d25f3442c318b8c8

Will be on the next testflight update and eventually to app store.
