### ISSUE TITLE
Publish .ipa in github releases

### ISSUE THREAD

**Issue by emanuelb** [Fonta1n3/FullyNoded#158]
Add .ipa file (iOS app) to the github releases as asset, which currently have only .dmg file for MACOSX
https://github.com/Fonta1n3/FullyNoded/releases

**Comment by Fonta1n3** [comment]
as far as I understand Apple does not allow "side loading" via an ipa file anymore... so this would be pointless? If I am missing something please educate me :)

**Comment by emanuelb** [comment]
not pointless at all, there are other reasons to publish it besides "side loading" which still might be possible in jailbroken devices, and also might be installed by using virtualization of iOS by corellium: (not sure, didn't test myself)
https://github.com/corellium/corellium-api#async-installpath-progress

Other purposes and usage of published .ipa besides installing it on device/virtualization are:
1. Reproducible builds, see this comment and issue for more details to understand why publishing the .ipa is needed: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/149#note_537109159
2. Looking at the file content after unzip, might report issues if found some after doing it.
3. Comparing the content of .ipa between versions with diffoscope https://diffoscope.org/ 
4. while no "open iOS" by default now, it might change in future like for example due to apple VS epic battle in courts.

And there probably other usages as well..

will open issue soon in walletscrutiny repo for adding FullyNoded & more iOS wallets to https://walletscrutiny.com

**Comment by yeru83** [comment]
Yes this is all a good idea.

**Comment by yeru83** [comment]
https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/149#note_537109159

**Comment by Fonta1n3** [comment]
@emanuelb thanks for bringing this to my attention. I will certainly add this for all future releases.

**Comment by Fonta1n3** [comment]
please see 0.2.18 latest release, it now includes an ipa, its signature and sha256sums
