### ISSUE TITLE
support for older macOS operating systems?

### ISSUE THREAD

**Issue by bradlives** [Fonta1n3/FullyNoded#159]
Old Mac hardware is great for nodes, but the new OS will slow old hardware down.

At a min I'd want to run this on 10.13.6 high Sierra. The latest requires Big Sur, quite a big leap.

**Comment by Fonta1n3** [comment]
For now you can run a version prior to 0.2.19 and it should work to Mojave.

**Comment by Fonta1n3** [comment]
Just FYI I just committed a change that does make the entire app backward compatible to ios13 and Mojave. Unfortunately you may lose QR scanning ability on Mojave...

**Comment by bradlives** [comment]
> Just FYI I just committed a change that does make the entire app backward compatible to ios13 and Mojave. Unfortunately you may lose QR scanning ability on Mojave...

Legend,
My recent request was because after High Sierra, macOS’s made 2014 hardware run slow, limped along on Catalina for a while, but just recently downgraded the OS again for speed, but then I found FN wasn't supported and I couldn’t compile down without BigSur xtools. Long story short, just bought macMin2018, runs headless via vpn, Bug Sur OS, FN running great, should’ve upgraded ages ago!

Next step setting up my lightning node ‘very exciting times’ 

Love your work, FN is the perfect solution for me!
