### ISSUE TITLE
Wallet manager layout problem on iPhone SE

### ISSUE THREAD

**Issue by dimaatmelodromru** [Fonta1n3/FullyNoded#16]
Text is unscrollable
![F20909E8-51DF-4DC8-8771-7227425654F9](https://user-images.githubusercontent.com/4951450/79401031-99c40500-7f90-11ea-8c31-db35d693cbaa.png)

**Comment by Fonta1n3** [comment]
fixed as per https://github.com/Fonta1n3/FullyNoded/commit/efec247856e16227eee0d4e1d25f3442c318b8c8

Will be on the next testflight update and eventually to app store.
