### ISSUE TITLE
Incoming/outgoing transactions do not show up

### ISSUE THREAD

**Issue by Lobbelt** [Fonta1n3/FullyNoded#174]
I created a Fully Noded wallet using the iOS Fully Noded app (iPhone 11 Pro).  For context: my Fully Noded app is connected to a Raspiblitz full node. 

I created an invoice using the app and sent some BTC to it. It does not show up in the wallet under transactions or unlocked UTXO's. Then I noticed under "advanced" that there are actually 2 different wallets: "wallet.dat" and the Fully Noded wallet. 

When I activated "wallet.dat" instead of the Fully Noded wallet, the transaction still did not show up but the UTXO was available under the "utxo's" tab.

Not sure what I did wrong or how I can make sure ALL transactions are shown in my wallet, and not just in the UTXO list of only one specific (separate?) wallet (wallet.dat) that I did not create?

**Comment by Fonta1n3** [comment]
Is your node fully synced? If it isn't then transactions and utxos will not show up.

The wallet.dat is the default
Wallet bitcoin core automatically creates for you.

**Comment by Fonta1n3** [comment]
The other thing to check... Do you have any lightning nodes added to FN?

**Comment by Fonta1n3** [comment]
closing as I do not think this is an actual bug. If you can reliably reproduce this issue please reopen and share a screen recording.
