### ISSUE TITLE
Instructions for performing reproducible builds

### ISSUE THREAD

**Issue by achow101** [Fonta1n3/FullyNoded#176]
I'm told that FullyNoded can be reproducibly built, but I am unable to find instructions for doing so. It would be nice to have clear documentation on how to do such a build, particularly for people who may be unfamiliar with XCode and unfamiliar with developing for MacOS and iOS in general.

**Comment by Fonta1n3** [comment]
Hi Andrew thanks for raising the issue. Not sure how that slipped through the cracks! 

I have added the instructions to the readme [here](https://github.com/Fonta1n3/FullyNoded#reproducible-builds) and have also added the signed source code as zip and tar files to the [releases](https://github.com/Fonta1n3/FullyNoded/releases).

Please let me know if the instructions are still lacking or if you have any questions. It is apparently not possible to get reproducible builds for App Store downloads so you must either double click the `dmg` or `ipa` to install on your mac, or build from source using Xcode which I have also included instructions for [here](https://github.com/Fonta1n3/FullyNoded#build-from-source), worth noting that bc the dependencies are committed in the app it is very easy to build and should just work without much headache.

**Comment by Fonta1n3** [comment]
Closing this as I think I have done all I can do, if not please reopen and let me know.
