### ISSUE TITLE
SSL error when connecting to LND via Tor

### ISSUE THREAD

**Issue by aetikon** [Fonta1n3/FullyNoded#188]
**Describe the bug**

We get an SSL error when attempting to connect to LND on MyNodeBTC.

**To Reproduce**
1. In myNodeBtc, pair a wallet using Lightning (REST + Tor)
2. Load the QR code in FN
3. See error

**Expected behavior**

No error

**Screenshots**

![FN-error](https://user-images.githubusercontent.com/23173700/136618094-9837e8b7-2c05-49e0-819d-71c8041e4347.jpeg)

**Device:**
 - Model: iPhone
 - OS: iOS

**Additional context**

Apparently the alert is triggered in **View Controllers/Settings/Node Manager/Lightning/AddPeerViewController.swift**:174

**Comment by Fonta1n3** [comment]
Ive also experienced this issue on a rare occasion. For me rebooting Tor on the server seemed to always fix the issue. Can you try to reboot tor on your mynode and also force quit and reopen FullyNoded (forces tor to reboot on FN) and see if it resolves your issue?

**Comment by aetikon** [comment]
We rebooted MyNode and force closed FN on the iPhone, but that didn't resolve the problem.  MyNode is fully updated (bitcoin core 22.0.0 and LND 0.13.3)

We also configured the iPhone to connect to MyNode's VPN and attempted to connect FN to LND directly using REST + Local IP, but the connection failed with "The operation couldn't be completed. Invalid argument."

**Comment by Fonta1n3** [comment]
> We rebooted MyNode and force closed FN on the iPhone, but that didn't resolve the problem. MyNode is fully updated (bitcoin core 22.0.0 and LND 0.13.3)
> 
> We also configured the iPhone to connect to MyNode's VPN and attempted to connect FN to LND directly using REST + Local IP, but the connection failed with "The operation couldn't be completed. Invalid argument."

https://github.com/Fonta1n3/FullyNoded/commit/a87d5e74dc2a3c0feed475b1999cb20ea98d1ddc should fix this, if you can build from source and test that'd be great. Tor only for now, local connection coming soon.

**Comment by Fonta1n3** [comment]
For the record I can't test as I do not have a mynode, for my Nodl the old code and this code works fine.

**Comment by Fonta1n3** [comment]
v0.2.28 should also work with localhost for LND and c-lightning 👍🏻
