### ISSUE TITLE
Feature: Use a signer without associated wallet 

### ISSUE THREAD

**Issue by deepy420** [Fonta1n3/FullyNoded#203]
**Is your feature request related to a problem? Please describe.**

It seems that currently the only way to use a signer to sign a transaction is to have a wallet associated with it. Otherwise the interface prompts to first create a wallet for it. I don't want to create a wallet for it as then the Bitcoin node will store the unencrypted wallet.

**Describe the solution you'd like**

Either Fully Noded should allow the wallet to only be stored locally on the phone and perhaps use Electrum or it should allow a signer to sign a transaction without an associated wallet.

**Comment by Fonta1n3** [comment]
It actually works just fine to sign any psbt you add even if there is no associated wallet.

Just add the bip39 signer as normal then tap the `sign / send / join` button on the active wallet view to upload as psbt as normal. it will automatically try and sign the psbt with each signer regardless of what wallets exist.

It is very important that the psbt inputs contain the `bip32 derivs`, if the psbt does not contain that info then of course it won't be able to sign.

**Comment by deepy420** [comment]
>>It will automatically try and sign the psbt with each signer regardless of what wallets exist.

Maybe it didn't work because I need to manually enter my passphrase? You mentioned that it will "automatically" try to sign.

No wallet existed and I tried to open the psbt, and it just prompted me saying I need to create a wallet first. Maybe at least one wallet needs to exist even if it's not the wallet for that pbst?

>>It is very important that the psbt inputs contain the bip32 derivs

I'm not technical enough to understand how to check this. I just downloaded and transferred the pbst via iPhone airdrop from Sparrow Wallet. Any insight on how to check would be appreciated. Thanks!

**Comment by Fonta1n3** [comment]
To enter the passphrase when signing go to `settings` > `security center` > `prompt for passphrase`

Just create a dummy wallet to avoid that prompt, it should work fine after that. I'll test and fix that if it is the case.

Sparrow would include the bip32 derive I beleive. It basically just means that each input you are trying to sign for includes a derivation path (in the psbt itself) so that an offline signer (Fully Noded in this case) would know exactly which private key is needed to sign the psbt with.

**Comment by deepy420** [comment]
It does work for me when I create any wallet (not related to the psbt). I just tested that after receiving your reply. The error message didn't make that clear and I thought I was being forced to create the wallet that matches that psbt, which I really didn't want to do because I didn't want that info on the node. Thanks for the clarification!
