### ISSUE TITLE
Exporting a FN wallet to FN on another phone.

### ISSUE THREAD

**Issue by CoderBoogs** [Fonta1n3/FullyNoded#213]
When I exported my wallet to FN using the QR code recommended for FN exports on to my other phone is this a watch only Wallet? I was trying to send you a donation as a test transaction and FN froze when trying to sign.

**Comment by Fonta1n3** [comment]
Signers and wallets are treated as operate entities, you back up wallets with the QR in watch-only formate. You backup signers on paper of metal written down offline.

If you recovered a wallet with a QR it is watch only. Just add the signer again.

**Comment by CoderBoogs** [comment]
Thanks
