### ISSUE TITLE
Have self transfers to show up in wallet hx for possiblity of using bumpfee

### ISSUE THREAD

**Issue by ideal-coffee7850** [Fonta1n3/FullyNoded#214]
When dividing utxos or doing other self transfers it would be helpful to add back the ability to see these transactions in wallet hx. When there's still 0 confirmations, this would be helpful to add a bumpfee. The self transfers are visible on the utxo's page, but there is not ability to bumpfee from there, so seeing them in the wallet hx and having the ability to bumpfee from there could be helpful.

**Comment by Fonta1n3** [comment]
should be fixed for 0.3.1, please let me know
