### ISSUE TITLE
Fetching historic rate no longer working

### ISSUE THREAD

**Issue by CoderBoogs** [Fonta1n3/FullyNoded#223]
**Describe the bug**
Trying to fetching the USD amount of a transaction that's in my wallet. 

**To Reproduce**
1. Go to wallet 
2. Select a transaction 
3. Click on blue link that says "fetch"

**Expected behavior**
After loading FN populates the USD amount when the txn was confirmed in the wallet 

**Screenshots**
Unable to attach

**Device (please complete the following information):**
 - Model: iPhone 12
 - OS: iOS 15
 - Version 15.5

**Additional context**
Used to work fine just the last few txn it's failing and in the error message it says let FN know

**Comment by Fonta1n3** [comment]
duplicate to #221
