### ISSUE TITLE
can't import or create wallet: "method not found"

### ISSUE THREAD

**Issue by ExperiBass** [Fonta1n3/FullyNoded#241]
**Describe the bug**
Attempting to import or create a wallet results in the error "method not found" appearing.

**To Reproduce**
1. Attempt to create or import a wallet.
2. See error.

**Expected behavior**
The wallet would be imported/created without a hitch.

**Device (please complete the following information):**
 - Model: iPhone 12
 - OS: iOS 15.4.1
 - FullyNoded Version: 0.4.6

**Additional context**

**Comment by Fonta1n3** [comment]
Have you added a bitcoin core node? 

Does your bitcoin.conf disable the wallet?

**Comment by ExperiBass** [comment]
> Does your bitcoin.conf disable the wallet?

that's probably it, i'll rebuild and check again.
