### ISSUE TITLE
iCloud Health Check displays error message even when the decrypt was succesful

### ISSUE THREAD

**Issue by PaulADW** [Fonta1n3/FullyNoded#243]
**Describe the bug**
Once you try to do a health check for your iCloud Backup, FN iOS gives you the error message like 'Try with another password', even though the password you provided was able to decrypt the backup. 

**To Reproduce**
Go to settings, create an iCloud backup password
Confirm it in the popup to make sure you didn't misspell anything. 

Tap on "iCloud Health Check"
Enter the password you just set

The app still tells you : "Decryption failed", even though it now does display my signer unencrypted etc. 

**Expected behavior**
Should display "Decryption succeeded" when it has indeed succeeded. 

**Screenshots**

**Device (please complete the following information):**
 - Model: iPhone 14Pro
 - OS: iOS
 - Version 16.2

**Comment by Fonta1n3** [comment]
Hey Paul, I am removing some fat from Fully Noded and iCloud got the chop for now, I plan to add it back again but it will be much simpler (just a toggle on/off).
