### ISSUE TITLE
v0.6.5 on iPad mini 6 Security Center button incorrent

### ISSUE THREAD

**Issue by bleeee** [Fonta1n3/FullyNoded#244]
Is there an existing issue for this?
 I have searched the existing issues
Current behaviour
v0.6.5 on iPad mini 6 Security Center button incorrent

2FA button is actually app password
app password button is wall set pass phrase

all wallet encryption button is biometrics

Maybe caused by added tor authentication while not corrently arrangement other buttons

**Comment by Fonta1n3** [comment]
This is fixed in v0.6.6
