### ISSUE TITLE
Please add copy rights to TorClient

### ISSUE THREAD

**Issue by SwenVanZanten** [Fonta1n3/FullyNoded#3]
Hi there, I see in this project @FontaineDenton copied the file:
https://github.com/FontaineDenton/FullyNoded/blob/master/BitSense/Helpers/New%20Group/TorClient.swift

From this file:
https://github.com/vergecurrency/vIOS/blob/master/VergeiOS/Http/TorClient.swift

The original file has copy rights under Verge Currency.
Please add these copy rights to your file.

Thanks in advance! 👍

**Comment by Fonta1n3** [comment]
Will do! Apologies for the delayed response.

**Comment by Fonta1n3** [comment]
added
