### ISSUE TITLE
Look for a best of breed pragmatic Q&A format for a github page

### ISSUE THREAD

**Issue by henkvancann** [Fonta1n3/FullyNoded#34]
The telegram chat is a rich source of knowledge about FN. However it's unstructured, it often lacks context and only comprehensible for experienced people in bitcoin.

An *initial shot* to create a Q&A, alongside the Telegram chat 'as we go', that lowers the threshold to enter the FN arena and increases understandability of the information, I offered this pull request: https://github.com/Fonta1n3/FullyNoded/pull/33.

Many Q&As exist on github. This FN project could adopt a Q&A format that really works sophisticated. The [present issue](https://github.com/Fonta1n3/FullyNoded/issues/34) can be closed by Looking for - and finding - a best of breed pragmatic Q&A format for a Q&A github page. Suggestions in comments, please.

**Comment by Fonta1n3** [comment]
I am happy with this format: https://github.com/Fonta1n3/FullyNoded/blob/master/Docs/QandA.md

Thanks for the contribution!
