### ISSUE TITLE
The Q and A needs categories

### ISSUE THREAD

**Issue by henkvancann** [Fonta1n3/FullyNoded#39]
And it could be handy to put questions in more than one category.

Don't know whether we can pick / copy an existing mark down solution for github from somewhere.

**Comment by henkvancann** [comment]
Rudimentary solution, Drawback: single word links, no spaces allowed.

# Jump table to categories
1. [General](#General)
2. [Standup](#Standup)
3. [Userinterface](#Userinterface)
4. [Import](#Import)
5. [Export](#Export)
6. [Wallets](#Wallets)
7. [Connection](#Connection)

**Comment by Fonta1n3** [comment]
lgtm, I think this can be closed?

**Comment by henkvancann** [comment]
Yes
  

  

  

  
  
  
  
  
>
