### ISSUE TITLE
Look into adding support for WireGuard

### ISSUE THREAD

**Issue by Fonta1n3** [Fonta1n3/FullyNoded#56]
https://git.zx2c4.com/wireguard-apple/about/

**Comment by keeshux** [comment]
As a means to provide an alternative to Tor?

**Comment by Fonta1n3** [comment]
As a potential additional option.

**Comment by Fonta1n3** [comment]
> As a means to provide an alternative to Tor?

If you use wireguard or another vpn you should be able to add the ip and port for it now as long as the host can access bitcoind rpcport 8332 👍
