### ISSUE TITLE
Add cookie authentication to Tor Hidden Service

### ISSUE THREAD

**Issue by 05nelsonm** [Fonta1n3/FullyNoded#6]
Opening port 8332 up via a Tor HS w/o properly generating a base32 keypair allows anyone and everyone who has the onion address to issue commands to it.

Setting up proper authentication will require that only the user with the private key pair has access to the hidden service.

A good guide for doing so:
https://matt.traudt.xyz/p/FgbdRTFr.html

**Comment by Fonta1n3** [comment]
Appreciate the issue, for sure once I fix the current bug on devices I will add ability for user to add an auth key for their V3.

**Comment by Fonta1n3** [comment]
Added to latest update
