### ISSUE TITLE
Tapping refresh button in Tor V3 Authentication on iPad not responsive

### ISSUE THREAD

**Issue by henkvancann** [Fonta1n3/FullyNoded#60]
In FN v.0.1.64 on a IpadOS 13.5.1. and choosing settings > security center > Tor V3 Authentication.

https://github.com/Fonta1n3/FullyNoded/blob/master/Readme.md#connect-your-own-node says
"tap the refresh button to create keys out of band or .."

Tapping refresh button does nothing except for turning grey instead of blue.

Context: I was fighting the 'Internet connection appears to be offline' response from Node Manager in FN on Ipad. 

I'd like to generate a keypair and add the public key to  authorized_clients dir in Tor HiddenServices on my node.

**Comment by Fonta1n3** [comment]
Should be fixed in next update if not reopen this

**Comment by henkvancann** [comment]
Tested the refresh button. That worked now + I got the warning pop-up ("might loose connection")

However, I added the public key to fullynoded.auth and I tried with and without a newline after the public key, but no connection anymore.

ls- l in /var/lib/tor/FullyNodedV3/authorized_clients/:

drwx------  3 hvancann  admin    96B Aug  8 16:41 .
drwx------  6 hvancann  admin   192B Aug  8 16:42 ..
-rw-r--r--@ 1 hvancann  staff    71B Aug  8 16:41 fullynoded.auth

**Comment by henkvancann** [comment]
Forget about it, in the meanwhile my node had crashed, so that was the reason I didn't get connection.
