### ISSUE TITLE
Project folders renamed and old path remembered for core data.

### ISSUE THREAD

**Issue by VictrixBV** [Fonta1n3/FullyNoded#68]
<img width="1339" alt="Screen Shot 2020-08-17 at 12 41 09" src="https://user-images.githubusercontent.com/25705055/90390356-78cd0700-e08b-11ea-8489-d7930b8c55d6.png">

**Comment by VictrixBV** [comment]
Solved by changing directory for BitSense.xcdatamodeld (from -old to actual) in Xcode-Build Phases-Compile Sources.
Then a new error: no libwally module found.
Quick and (very) dirty solved: by copying libwally directories from GordianWallet/Carthage and compiling in FN. Also created a temporary missing /MyStuff/temp/FINAL-Fully Noded-logo/ios/iTunesArtWork@2x.png.
Xcode Build Succeeded (with some warnings) now and is functional.

**Comment by Fonta1n3** [comment]
Thanks, very helpful. Will fix.

**Comment by Fonta1n3** [comment]
@VictrixBV the Checkouts directory was in the `.gitignore`, I had gone back and forth on that and forgot.. Please if you wouldn't mind trying again you should no longer get that error.

**Comment by VictrixBV** [comment]
Tried again and issue solved. Thanks!
