### ISSUE TITLE
Error "The data couldn't be read because its not in the correct format"

### ISSUE THREAD

**Issue by mcsnubbs** [Fonta1n3/FullyNoded#9]
![IMG_5881](https://user-images.githubusercontent.com/54904977/67157598-5009a300-f2fc-11e9-9cf0-9767199e94d9.PNG)

Im using the latest test flight to connect to a myNode with SSH. Although it connects, it gives me this error whenever I try any of the wallet features.

**Comment by Fonta1n3** [comment]
is your node still doing IBD?

**Comment by mcsnubbs** [comment]
No its up and running with both lightning and electrumrs working appropriately

**Comment by indexgenuiner** [comment]
Backup

**Comment by Fonta1n3** [comment]
That is the error you can get if your rpc credentials are incorrect. Are you sure there were no typos and that you got them from the correct bitcoin.conf file?

What OS is your node running on? Nodl, mac, linux?

**Comment by mcsnubbs** [comment]
Just re-entered RPC credentials with no avail...

The "myNodeBTC" runs on a raspberry pi; Linux. mynodebtc.com

**Comment by Fonta1n3** [comment]
Are you able to ssh into it with another computer?

**Comment by mcsnubbs** [comment]
Yes

**Comment by Fonta1n3** [comment]
If you get connected from another computer then issue the following command substituting the username and password with your own.

```
curl --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockchaininfo", "params":[] }' -H 'content-type: text/plain;' http://yourRPCUsername:yourRPCPassword@127.0.0.1:8332/
```

Let me know what the response is.

**Comment by indexgenuiner** [comment]
@backup

**Comment by indexgenuiner** [comment]
All

**Comment by indexgenuiner** [comment]
@mcsnubbs

**Comment by Fonta1n3** [comment]
not an issue with the app
